# Copyright(C) 2025 Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: MIT

# Use ROCm 7.2 with PyTorch 2.7.1 and Python 3.12
init_image: "rocm/pytorch:rocm7.2_ubuntu24.04_py3.12_pytorch_release_2.7.1"

build_arguments:
- "PYTHON_VERSION=3.12"

environment_variables: #TODO: Update with your own HF token
  - "HF_TOKEN="

# Make sure calibration is persistent and models are available after ryzer exit
volume_mappings:
- "~/.cache/huggingface/lerobot/calibration/:/root/.cache/huggingface/lerobot/calibration"
- "$PWD/packages/robotics/lerobot/mounted:/ryzers/mounted"

# TODO: change to your robot and video device locations:
#docker_extra_run_flags:
#    - "--device=/dev/ttyACM_leader:/dev/ttyACM_leader"
#    - "--device=/dev/ttyACM_follower:/dev/ttyACM_follower"
#    - "--device=/dev/webcam_top:/dev/webcam_top"
#    - "--device=/dev/webcam_front:/dev/webcam_front"
